### ISSUE TITLE
use el.contains(el)

### ISSUE THREAD

**Issue by matthewmueller** [component/within-element#1]
Probably better: https://developer.mozilla.org/en-US/docs/Web/API/Node.contains

``` js
module.exports = function within (child, parent) {
  var node = child;
  while (node = node.parentNode) {
    if (node == parent) return true;
  }
  return false;
};
```

To:

``` js
function within (child, parent) {
  return parent.contains(child);
}
```

;-D

**Comment by TooTallNate** [comment]
Nice new gravatar bro :bear:

**Comment by matthewmueller** [comment]
haha thanks man :-D

**Comment by TooTallNate** [comment]
So I'm down to use `.contains()` but from reading up on it there's a few edge-cases we'd have to catch as well, like on old IE it doesn't work on text nodes. Probably other stuff.

**Comment by matthewmueller** [comment]
hmm, yah not sure if/when that textnode bug has been resolved. this might be safer, while contains is faster.

**Comment by jonathanong** [comment]
i'd rather write a polyfill that overwrites the implementation if it's incorrect and just use `node.contains()` :P fuck all these tiny libs man lol

**Comment by rauchg** [comment]
-1 on polyfill. `require('contains')`

**Comment by matthewmueller** [comment]
added in master
